language: cpp
script: bash -e .travis.sh
sudo: required
dist: trusty

before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - sleep 3 # give xvfb some time to start

# ignore this branch because it is only a mirror of master
branches:
  except:
    - _widelands_dev_widelands_trunk

# Let travis add additional repos for us (https://docs.travis-ci.com/user/migrating-from-legacy/#Adding-APT-Sources)
# These are based on a whitelist, see https://github.com/travis-ci/apt-source-whitelist for details
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - cmake
      - libboost-dev
      - libboost-regex-dev
      - libboost-system-dev
      - libboost-test-dev
      - libglew-dev
      - libicu-dev
      - libpng-dev
      - libsdl2-dev
      - libsdl2-image-dev
      - libsdl2-mixer-dev
      - libsdl2-ttf-dev
      - python-pip
      - zlib1g-dev

matrix:
  include:
    - compiler: clang
      env: CLANG_VERSION="3.4" BUILD_TYPE="Debug"
    - compiler: clang
      env: CLANG_VERSION="3.5" BUILD_TYPE="Debug"
    - compiler: clang
      env: CLANG_VERSION="3.9" BUILD_TYPE="Debug"
    - compiler: clang
      env: CLANG_VERSION="4.0" BUILD_TYPE="Debug"
    - compiler: clang
      env: CLANG_VERSION="3.4" BUILD_TYPE="Release"
    - compiler: clang
      env: CLANG_VERSION="3.5" BUILD_TYPE="Release"
    - compiler: clang
      env: CLANG_VERSION="3.9" BUILD_TYPE="Release"
    - compiler: clang
      env: CLANG_VERSION="4.0" BUILD_TYPE="Release"
    - compiler: gcc
      env: GCC_VERSION="4.8" BUILD_TYPE="Debug"
    - compiler: gcc
      env: GCC_VERSION="4.9" BUILD_TYPE="Debug"
    - compiler: gcc
      env: GCC_VERSION="6" BUILD_TYPE="Debug"
    - compiler: gcc
      env: GCC_VERSION="7" BUILD_TYPE="Debug"
    - compiler: gcc
      env: GCC_VERSION="4.8" BUILD_TYPE="Release"
    - compiler: gcc
      env: GCC_VERSION="4.9" BUILD_TYPE="Release"
    - compiler: gcc
      env: GCC_VERSION="6" BUILD_TYPE="Release"
    - compiler: gcc
      env: GCC_VERSION="7" BUILD_TYPE="Release"
