language: cpp
script: bash -e .travis.sh
sudo: required
dist: trusty

matrix:
  include:
     - compiler: clang
       env: CLANG_VERSION="3.4" BUILD_TYPE="Debug"
     - compiler: clang
       env: CLANG_VERSION="3.5" BUILD_TYPE="Debug"
     - compiler: clang
       env: CLANG_VERSION="3.6" BUILD_TYPE="Debug"
     - compiler: clang
       env: CLANG_VERSION="3.7" BUILD_TYPE="Debug"
     - compiler: clang
       env: CLANG_VERSION="3.4" BUILD_TYPE="Release"
     - compiler: clang
       env: CLANG_VERSION="3.5" BUILD_TYPE="Release"
     - compiler: clang
       env: CLANG_VERSION="3.6" BUILD_TYPE="Release"
     - compiler: clang
       env: CLANG_VERSION="3.7" BUILD_TYPE="Release"
     - compiler: gcc
       env: GCC_VERSION="4.7" BUILD_TYPE="Debug"
     - compiler: gcc
       env: GCC_VERSION="4.8" BUILD_TYPE="Debug"
     - compiler: gcc
       env: GCC_VERSION="4.9" BUILD_TYPE="Debug"
     - compiler: gcc
       env: GCC_VERSION="5" BUILD_TYPE="Debug"
     - compiler: gcc
       env: GCC_VERSION="4.7" BUILD_TYPE="Release"
     - compiler: gcc
       env: GCC_VERSION="4.8" BUILD_TYPE="Release"
     - compiler: gcc
       env: GCC_VERSION="4.9" BUILD_TYPE="Release"
     - compiler: gcc
       env: GCC_VERSION="5" BUILD_TYPE="Release"
