language: cpp
before_install: bash -e .travis.sh
sudo: required
dist: trusty

branches:
  except:
    - _widelands_dev_widelands_trunk

env:
  global:
   # The next declaration is the encrypted COVERITY_SCAN_TOKEN, created
   #   via the "travis encrypt" command using the project repo's public key
   - secure: "QFKfKCTDzhIpO12glYXbC285SPOTxBmdsi0UzsQJ6t1T43Z6n6eLVT4XnB90H4h4ri+sKyF2Qc0T/mshvPS/U74SENTb8Hz8w2NOQOpIII+YDGPGABidupnJtgsjOk36n+id8ZxIym40/uoZEOUYCkdQM2AZex1sNKTwlGPr7X8="

matrix:
  include:
     - compiler: gcc
       env: GCC_VERSION="5" BUILD_TYPE="Release"

addons:
  coverity_scan:
    project:
      name: "widelands/widelands"
      description: "Build submitted via Travis CI"
    notification_email: mail@example.com
    build_command_prepend: "mkdir build && cd build && cmake -G Ninja .. -DCMAKE_BUILD_TYPE:STRING=\"$BUILD_TYPE\""
    build_command: "ninja"
    branch_pattern: coverity_scan
